### ISSUE TITLE
New ff4fe 2p backgrounds and splash screens

### ISSUE THREAD

**Issue by jsnkuhn** [Rando-Mania/RandoTracker#148]
per SchalaKitty's request we have 2 new backgrounds for community club showcases. That's 2p layouts. 

images are here: https://www.dropbox.com/s/cy59dzuiz3hb9do/FF4FE-ClubShowcase-NewAssets.zip?dl=0

Wacky Races is for Sat. Pink Puff is for next Thursday. Should probably be able to all be done at once though.

**Comment by jsnkuhn** [comment]
new drop box link: https://www.dropbox.com/s/nrplogqehse0umt/FF4FE-ClubShowcase-NewAssets-Redone.zip?dl=0

**Comment by Soleras3** [comment]
I'll pick this up (I'd assign to myself but doesn't seem like I can yet)

**Comment by jsnkuhn** [comment]
seems like this is all done and no follow up is needed so closing
